#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5D2EEE6F6F349D7C (tim@centricular.com)
#
Name     : gst-plugins-base
Version  : 1.16.0
Release  : 36
URL      : https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.16.0.tar.xz
Source0  : https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.16.0.tar.xz
Source99 : https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.16.0.tar.xz.asc
Summary  : GStreamer Multimedia Framework Base Plugins
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: gst-plugins-base-bin = %{version}-%{release}
Requires: gst-plugins-base-data = %{version}-%{release}
Requires: gst-plugins-base-lib = %{version}-%{release}
Requires: gst-plugins-base-license = %{version}-%{release}
Requires: gst-plugins-base-locales = %{version}-%{release}
Requires: gst-plugins-base-man = %{version}-%{release}
BuildRequires : buildreq-kde
BuildRequires : buildreq-meson
BuildRequires : clutter-dev
BuildRequires : docbook-xml
BuildRequires : glu-dev
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gst-plugins-base-dev
BuildRequires : gstreamer-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libogg-dev
BuildRequires : libvorbis-dev
BuildRequires : libxslt-bin
BuildRequires : mesa-dev
BuildRequires : opus-dev
BuildRequires : orc
BuildRequires : orc-dev
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtk+-x11-3.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(sdl)
BuildRequires : pkgconfig(theoradec)
BuildRequires : pkgconfig(theoraenc)
BuildRequires : pkgconfig(vorbis)
BuildRequires : pkgconfig(vorbisenc)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xv)
BuildRequires : pkgconfig(zlib)
BuildRequires : qtbase-dev
BuildRequires : valgrind

%description
The RTP libraries
---------------------
RTP Buffers
-----------
The real time protocol as described in RFC 3550 requires the use of special
packets containing an additional RTP header of at least 12 bytes. GStreamer
provides some helper functions for creating and parsing these RTP headers.
The result is a normal #GstBuffer with an additional RTP header.
RTP buffers are usually created with gst_rtp_buffer_new_allocate() or
gst_rtp_buffer_new_allocate_len(). These functions create buffers with a
preallocated space of memory. It will also ensure that enough memory
is allocated for the RTP header. The first function is used when the payload
size is known. gst_rtp_buffer_new_allocate_len() should be used when the size
of the whole RTP buffer (RTP header + payload) is known.
When receiving RTP buffers from a network, gst_rtp_buffer_new_take_data()
should be used when the user would like to parse that RTP packet. (TODO Ask
Wim what the real purpose of this function is as it seems to simply create a
duplicate GstBuffer with the same data as the previous one). The
function will create a new RTP buffer with the given data as the whole RTP
packet. Alternatively, gst_rtp_buffer_new_copy_data() can be used if the user
wishes to make a copy of the data before using it in the new RTP buffer.
It is now possible to use all the gst_rtp_buffer_get_*() or
gst_rtp_buffer_set_*() functions to read or write the different parts of the
RTP header such as the payload type, the sequence number or the RTP
timestamp. The use can also retreive a pointer to the actual RTP payload data
using the gst_rtp_buffer_get_payload() function.

%package bin
Summary: bin components for the gst-plugins-base package.
Group: Binaries
Requires: gst-plugins-base-data = %{version}-%{release}
Requires: gst-plugins-base-license = %{version}-%{release}

%description bin
bin components for the gst-plugins-base package.


%package data
Summary: data components for the gst-plugins-base package.
Group: Data

%description data
data components for the gst-plugins-base package.


%package dev
Summary: dev components for the gst-plugins-base package.
Group: Development
Requires: gst-plugins-base-lib = %{version}-%{release}
Requires: gst-plugins-base-bin = %{version}-%{release}
Requires: gst-plugins-base-data = %{version}-%{release}
Provides: gst-plugins-base-devel = %{version}-%{release}
Requires: gst-plugins-base = %{version}-%{release}

%description dev
dev components for the gst-plugins-base package.


%package doc
Summary: doc components for the gst-plugins-base package.
Group: Documentation
Requires: gst-plugins-base-man = %{version}-%{release}

%description doc
doc components for the gst-plugins-base package.


%package lib
Summary: lib components for the gst-plugins-base package.
Group: Libraries
Requires: gst-plugins-base-data = %{version}-%{release}
Requires: gst-plugins-base-license = %{version}-%{release}

%description lib
lib components for the gst-plugins-base package.


%package license
Summary: license components for the gst-plugins-base package.
Group: Default

%description license
license components for the gst-plugins-base package.


%package locales
Summary: locales components for the gst-plugins-base package.
Group: Default

%description locales
locales components for the gst-plugins-base package.


%package man
Summary: man components for the gst-plugins-base package.
Group: Default

%description man
man components for the gst-plugins-base package.


%prep
%setup -q -n gst-plugins-base-1.16.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555678880
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%reconfigure --disable-static --enable-theora
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1555678880
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gst-plugins-base
cp COPYING %{buildroot}/usr/share/package-licenses/gst-plugins-base/COPYING
cp gst-libs/gst/tag/licenses.c %{buildroot}/usr/share/package-licenses/gst-plugins-base/gst-libs_gst_tag_licenses.c
%make_install
%find_lang gst-plugins-base-1.0

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gst-device-monitor-1.0
/usr/bin/gst-discoverer-1.0
/usr/bin/gst-play-1.0

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GstAllocators-1.0.typelib
/usr/lib64/girepository-1.0/GstApp-1.0.typelib
/usr/lib64/girepository-1.0/GstAudio-1.0.typelib
/usr/lib64/girepository-1.0/GstGL-1.0.typelib
/usr/lib64/girepository-1.0/GstPbutils-1.0.typelib
/usr/lib64/girepository-1.0/GstRtp-1.0.typelib
/usr/lib64/girepository-1.0/GstRtsp-1.0.typelib
/usr/lib64/girepository-1.0/GstSdp-1.0.typelib
/usr/lib64/girepository-1.0/GstTag-1.0.typelib
/usr/lib64/girepository-1.0/GstVideo-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/gst-plugins-base/1.0/license-translations.dict

%files dev
%defattr(-,root,root,-)
/usr/include/gstreamer-1.0/gst/allocators/allocators-prelude.h
/usr/include/gstreamer-1.0/gst/allocators/allocators.h
/usr/include/gstreamer-1.0/gst/allocators/gstdmabuf.h
/usr/include/gstreamer-1.0/gst/allocators/gstfdmemory.h
/usr/include/gstreamer-1.0/gst/allocators/gstphysmemory.h
/usr/include/gstreamer-1.0/gst/app/app-enumtypes.h
/usr/include/gstreamer-1.0/gst/app/app-prelude.h
/usr/include/gstreamer-1.0/gst/app/app.h
/usr/include/gstreamer-1.0/gst/app/gstappsink.h
/usr/include/gstreamer-1.0/gst/app/gstappsrc.h
/usr/include/gstreamer-1.0/gst/audio/audio-buffer.h
/usr/include/gstreamer-1.0/gst/audio/audio-channel-mixer.h
/usr/include/gstreamer-1.0/gst/audio/audio-channels.h
/usr/include/gstreamer-1.0/gst/audio/audio-converter.h
/usr/include/gstreamer-1.0/gst/audio/audio-enumtypes.h
/usr/include/gstreamer-1.0/gst/audio/audio-format.h
/usr/include/gstreamer-1.0/gst/audio/audio-info.h
/usr/include/gstreamer-1.0/gst/audio/audio-prelude.h
/usr/include/gstreamer-1.0/gst/audio/audio-quantize.h
/usr/include/gstreamer-1.0/gst/audio/audio-resampler.h
/usr/include/gstreamer-1.0/gst/audio/audio.h
/usr/include/gstreamer-1.0/gst/audio/gstaudioaggregator.h
/usr/include/gstreamer-1.0/gst/audio/gstaudiobasesink.h
/usr/include/gstreamer-1.0/gst/audio/gstaudiobasesrc.h
/usr/include/gstreamer-1.0/gst/audio/gstaudiocdsrc.h
/usr/include/gstreamer-1.0/gst/audio/gstaudioclock.h
/usr/include/gstreamer-1.0/gst/audio/gstaudiodecoder.h
/usr/include/gstreamer-1.0/gst/audio/gstaudioencoder.h
/usr/include/gstreamer-1.0/gst/audio/gstaudiofilter.h
/usr/include/gstreamer-1.0/gst/audio/gstaudioiec61937.h
/usr/include/gstreamer-1.0/gst/audio/gstaudiometa.h
/usr/include/gstreamer-1.0/gst/audio/gstaudioringbuffer.h
/usr/include/gstreamer-1.0/gst/audio/gstaudiosink.h
/usr/include/gstreamer-1.0/gst/audio/gstaudiosrc.h
/usr/include/gstreamer-1.0/gst/audio/gstaudiostreamalign.h
/usr/include/gstreamer-1.0/gst/audio/streamvolume.h
/usr/include/gstreamer-1.0/gst/fft/fft-prelude.h
/usr/include/gstreamer-1.0/gst/fft/fft.h
/usr/include/gstreamer-1.0/gst/fft/gstfft.h
/usr/include/gstreamer-1.0/gst/fft/gstfftf32.h
/usr/include/gstreamer-1.0/gst/fft/gstfftf64.h
/usr/include/gstreamer-1.0/gst/fft/gstffts16.h
/usr/include/gstreamer-1.0/gst/fft/gstffts32.h
/usr/include/gstreamer-1.0/gst/gl/egl/gstegl.h
/usr/include/gstreamer-1.0/gst/gl/egl/gsteglimage.h
/usr/include/gstreamer-1.0/gst/gl/egl/gstgldisplay_egl.h
/usr/include/gstreamer-1.0/gst/gl/egl/gstglmemoryegl.h
/usr/include/gstreamer-1.0/gst/gl/gl-enumtypes.h
/usr/include/gstreamer-1.0/gst/gl/gl-prelude.h
/usr/include/gstreamer-1.0/gst/gl/gl.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/all_functions.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/base.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/blending.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/buffers.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/debug.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/eglimage.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/fbo.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/fixedfunction.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/gles.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/gstgl_compat.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/gstgl_gles2compat.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/opengl.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/query.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/shaders.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/sync.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/vao.h
/usr/include/gstreamer-1.0/gst/gl/gstgl_enums.h
/usr/include/gstreamer-1.0/gst/gl/gstgl_fwd.h
/usr/include/gstreamer-1.0/gst/gl/gstglapi.h
/usr/include/gstreamer-1.0/gst/gl/gstglbasefilter.h
/usr/include/gstreamer-1.0/gst/gl/gstglbasememory.h
/usr/include/gstreamer-1.0/gst/gl/gstglbuffer.h
/usr/include/gstreamer-1.0/gst/gl/gstglbufferpool.h
/usr/include/gstreamer-1.0/gst/gl/gstglcolorconvert.h
/usr/include/gstreamer-1.0/gst/gl/gstglcontext.h
/usr/include/gstreamer-1.0/gst/gl/gstgldebug.h
/usr/include/gstreamer-1.0/gst/gl/gstgldisplay.h
/usr/include/gstreamer-1.0/gst/gl/gstglfeature.h
/usr/include/gstreamer-1.0/gst/gl/gstglfilter.h
/usr/include/gstreamer-1.0/gst/gl/gstglformat.h
/usr/include/gstreamer-1.0/gst/gl/gstglframebuffer.h
/usr/include/gstreamer-1.0/gst/gl/gstglfuncs.h
/usr/include/gstreamer-1.0/gst/gl/gstglmemory.h
/usr/include/gstreamer-1.0/gst/gl/gstglmemorypbo.h
/usr/include/gstreamer-1.0/gst/gl/gstgloverlaycompositor.h
/usr/include/gstreamer-1.0/gst/gl/gstglquery.h
/usr/include/gstreamer-1.0/gst/gl/gstglrenderbuffer.h
/usr/include/gstreamer-1.0/gst/gl/gstglshader.h
/usr/include/gstreamer-1.0/gst/gl/gstglshaderstrings.h
/usr/include/gstreamer-1.0/gst/gl/gstglsl.h
/usr/include/gstreamer-1.0/gst/gl/gstglslstage.h
/usr/include/gstreamer-1.0/gst/gl/gstglsyncmeta.h
/usr/include/gstreamer-1.0/gst/gl/gstglupload.h
/usr/include/gstreamer-1.0/gst/gl/gstglutils.h
/usr/include/gstreamer-1.0/gst/gl/gstglviewconvert.h
/usr/include/gstreamer-1.0/gst/gl/gstglwindow.h
/usr/include/gstreamer-1.0/gst/gl/wayland/gstgldisplay_wayland.h
/usr/include/gstreamer-1.0/gst/gl/x11/gstgldisplay_x11.h
/usr/include/gstreamer-1.0/gst/pbutils/codec-utils.h
/usr/include/gstreamer-1.0/gst/pbutils/descriptions.h
/usr/include/gstreamer-1.0/gst/pbutils/encoding-profile.h
/usr/include/gstreamer-1.0/gst/pbutils/encoding-target.h
/usr/include/gstreamer-1.0/gst/pbutils/gstaudiovisualizer.h
/usr/include/gstreamer-1.0/gst/pbutils/gstdiscoverer.h
/usr/include/gstreamer-1.0/gst/pbutils/gstpluginsbaseversion.h
/usr/include/gstreamer-1.0/gst/pbutils/install-plugins.h
/usr/include/gstreamer-1.0/gst/pbutils/missing-plugins.h
/usr/include/gstreamer-1.0/gst/pbutils/pbutils-enumtypes.h
/usr/include/gstreamer-1.0/gst/pbutils/pbutils-prelude.h
/usr/include/gstreamer-1.0/gst/pbutils/pbutils.h
/usr/include/gstreamer-1.0/gst/riff/riff-ids.h
/usr/include/gstreamer-1.0/gst/riff/riff-media.h
/usr/include/gstreamer-1.0/gst/riff/riff-prelude.h
/usr/include/gstreamer-1.0/gst/riff/riff-read.h
/usr/include/gstreamer-1.0/gst/riff/riff.h
/usr/include/gstreamer-1.0/gst/rtp/gstrtcpbuffer.h
/usr/include/gstreamer-1.0/gst/rtp/gstrtp-enumtypes.h
/usr/include/gstreamer-1.0/gst/rtp/gstrtpbaseaudiopayload.h
/usr/include/gstreamer-1.0/gst/rtp/gstrtpbasedepayload.h
/usr/include/gstreamer-1.0/gst/rtp/gstrtpbasepayload.h
/usr/include/gstreamer-1.0/gst/rtp/gstrtpbuffer.h
/usr/include/gstreamer-1.0/gst/rtp/gstrtpdefs.h
/usr/include/gstreamer-1.0/gst/rtp/gstrtphdrext.h
/usr/include/gstreamer-1.0/gst/rtp/gstrtpmeta.h
/usr/include/gstreamer-1.0/gst/rtp/gstrtppayloads.h
/usr/include/gstreamer-1.0/gst/rtp/rtp-prelude.h
/usr/include/gstreamer-1.0/gst/rtp/rtp.h
/usr/include/gstreamer-1.0/gst/rtsp/gstrtsp-enumtypes.h
/usr/include/gstreamer-1.0/gst/rtsp/gstrtsp.h
/usr/include/gstreamer-1.0/gst/rtsp/gstrtspconnection.h
/usr/include/gstreamer-1.0/gst/rtsp/gstrtspdefs.h
/usr/include/gstreamer-1.0/gst/rtsp/gstrtspextension.h
/usr/include/gstreamer-1.0/gst/rtsp/gstrtspmessage.h
/usr/include/gstreamer-1.0/gst/rtsp/gstrtsprange.h
/usr/include/gstreamer-1.0/gst/rtsp/gstrtsptransport.h
/usr/include/gstreamer-1.0/gst/rtsp/gstrtspurl.h
/usr/include/gstreamer-1.0/gst/rtsp/rtsp-prelude.h
/usr/include/gstreamer-1.0/gst/rtsp/rtsp.h
/usr/include/gstreamer-1.0/gst/sdp/gstmikey.h
/usr/include/gstreamer-1.0/gst/sdp/gstsdp.h
/usr/include/gstreamer-1.0/gst/sdp/gstsdpmessage.h
/usr/include/gstreamer-1.0/gst/sdp/sdp-prelude.h
/usr/include/gstreamer-1.0/gst/sdp/sdp.h
/usr/include/gstreamer-1.0/gst/tag/gsttagdemux.h
/usr/include/gstreamer-1.0/gst/tag/gsttagmux.h
/usr/include/gstreamer-1.0/gst/tag/tag-enumtypes.h
/usr/include/gstreamer-1.0/gst/tag/tag-prelude.h
/usr/include/gstreamer-1.0/gst/tag/tag.h
/usr/include/gstreamer-1.0/gst/tag/xmpwriter.h
/usr/include/gstreamer-1.0/gst/video/colorbalance.h
/usr/include/gstreamer-1.0/gst/video/colorbalancechannel.h
/usr/include/gstreamer-1.0/gst/video/gstvideoaffinetransformationmeta.h
/usr/include/gstreamer-1.0/gst/video/gstvideoaggregator.h
/usr/include/gstreamer-1.0/gst/video/gstvideodecoder.h
/usr/include/gstreamer-1.0/gst/video/gstvideoencoder.h
/usr/include/gstreamer-1.0/gst/video/gstvideofilter.h
/usr/include/gstreamer-1.0/gst/video/gstvideometa.h
/usr/include/gstreamer-1.0/gst/video/gstvideopool.h
/usr/include/gstreamer-1.0/gst/video/gstvideosink.h
/usr/include/gstreamer-1.0/gst/video/gstvideotimecode.h
/usr/include/gstreamer-1.0/gst/video/gstvideoutils.h
/usr/include/gstreamer-1.0/gst/video/navigation.h
/usr/include/gstreamer-1.0/gst/video/video-anc.h
/usr/include/gstreamer-1.0/gst/video/video-blend.h
/usr/include/gstreamer-1.0/gst/video/video-chroma.h
/usr/include/gstreamer-1.0/gst/video/video-color.h
/usr/include/gstreamer-1.0/gst/video/video-converter.h
/usr/include/gstreamer-1.0/gst/video/video-dither.h
/usr/include/gstreamer-1.0/gst/video/video-enumtypes.h
/usr/include/gstreamer-1.0/gst/video/video-event.h
/usr/include/gstreamer-1.0/gst/video/video-format.h
/usr/include/gstreamer-1.0/gst/video/video-frame.h
/usr/include/gstreamer-1.0/gst/video/video-info.h
/usr/include/gstreamer-1.0/gst/video/video-multiview.h
/usr/include/gstreamer-1.0/gst/video/video-overlay-composition.h
/usr/include/gstreamer-1.0/gst/video/video-prelude.h
/usr/include/gstreamer-1.0/gst/video/video-resampler.h
/usr/include/gstreamer-1.0/gst/video/video-scaler.h
/usr/include/gstreamer-1.0/gst/video/video-tile.h
/usr/include/gstreamer-1.0/gst/video/video.h
/usr/include/gstreamer-1.0/gst/video/videodirection.h
/usr/include/gstreamer-1.0/gst/video/videoorientation.h
/usr/include/gstreamer-1.0/gst/video/videooverlay.h
/usr/lib64/gstreamer-1.0/include/gst/gl/gstglconfig.h
/usr/lib64/libgstallocators-1.0.so
/usr/lib64/libgstapp-1.0.so
/usr/lib64/libgstaudio-1.0.so
/usr/lib64/libgstfft-1.0.so
/usr/lib64/libgstgl-1.0.so
/usr/lib64/libgstpbutils-1.0.so
/usr/lib64/libgstriff-1.0.so
/usr/lib64/libgstrtp-1.0.so
/usr/lib64/libgstrtsp-1.0.so
/usr/lib64/libgstsdp-1.0.so
/usr/lib64/libgsttag-1.0.so
/usr/lib64/libgstvideo-1.0.so
/usr/lib64/pkgconfig/gstreamer-allocators-1.0.pc
/usr/lib64/pkgconfig/gstreamer-app-1.0.pc
/usr/lib64/pkgconfig/gstreamer-audio-1.0.pc
/usr/lib64/pkgconfig/gstreamer-fft-1.0.pc
/usr/lib64/pkgconfig/gstreamer-gl-1.0.pc
/usr/lib64/pkgconfig/gstreamer-pbutils-1.0.pc
/usr/lib64/pkgconfig/gstreamer-plugins-base-1.0.pc
/usr/lib64/pkgconfig/gstreamer-riff-1.0.pc
/usr/lib64/pkgconfig/gstreamer-rtp-1.0.pc
/usr/lib64/pkgconfig/gstreamer-rtsp-1.0.pc
/usr/lib64/pkgconfig/gstreamer-sdp-1.0.pc
/usr/lib64/pkgconfig/gstreamer-tag-1.0.pc
/usr/lib64/pkgconfig/gstreamer-video-1.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioAggregator.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioBaseSink.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioBaseSrc.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioCdSrc.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioClock.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioDecoder.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioEncoder.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioFilter.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioRingBuffer.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioSink.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioSrc.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstAudioVisualizer.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstColorBalance.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstColorBalanceChannel.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstDiscoverer.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstEncodingProfile.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLBaseFilter.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLBufferPool.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLColorConvert.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLContext.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLDisplay.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLDisplayWayland.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLFilter.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLFramebuffer.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLOverlayCompositor.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLSLStage.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLShader.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLUpload.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLViewConvert.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstGLWindow.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstNavigation.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstPhysMemoryAllocator.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstRTPBaseAudioPayload.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstRTPBaseDepayload.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstRTPBasePayload.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstRTSPExtension.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstRTSPMessage.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstRTSPUrl.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstStreamVolume.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstVideoAggregator.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstVideoAggregatorPad.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstVideoDecoder.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstVideoDirection.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstVideoEncoder.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstVideoFilter.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstVideoOrientation.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstVideoOverlay.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/GstVideoSink.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/annotation-glossary.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/api-index-deprecated.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/api-index-full.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/compiling.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gl.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-1.0.devhelp2
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-Audio-channels.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-Codec-utilities.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-Descriptions.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstAudio-IEC61937.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstAudio-meta.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstAudio.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstAudioConverter.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstAudioQuantize.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstEGLImage.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstExiftag.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstFFT.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstFFTF32.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstFFTF64.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstFFTS16.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstFFTS32.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLAPI.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLBaseMemory.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLBuffer.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLDisplayCocoa.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLDisplayEGL.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLDisplayX11.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLMemory.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLMemoryPBO.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLQuery.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLRenderbuffer.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLSL.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstGLSyncMeta.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstMIKEYMessage.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstMeta-for-RTP.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstMeta-for-video.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstRTCPBuffer.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstRTPBuffer.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstRTPPayloadInfo.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstRTPdefs.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstRTSPConnection.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstRTSPRange.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstRTSPTimeRange.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstRtphdrext.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstRtspdefs.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstSDPMessage.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstTagDemux.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstTagMux.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstTagXmpWriter.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVideo-Ancillary.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVideo-Codec-utility-function.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVideo.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVideoAffineTransformationMeta.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVideoChroma.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVideoDither.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVideoOverlayRectangle.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVideoPool.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVideoResampler.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVideoScaler.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstVorbisTag.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-GstXmptag.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-ID3-tag-utils.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-ISO-639-lang-mappings.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-Install-plugins.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-Licenses.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-Missing-plugins.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-OpenGL-Formats.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-OpenGL-Miscellaneous-Utilities.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-OpenGL-debugging.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-Pbutils.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-Riff-utilities.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-Tags.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-Version.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-appsink.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-appsrc.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-dmabuf.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-fdmemory.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gst-plugins-base-libs-gstglmemoryegl.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-allocators.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-app.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-audio.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-base-utils.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-ffft.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-libs-hierarchy.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-mikey.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-plugins-base.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-riff.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-rtp.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-rtsp.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-sdp.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-tag.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-video.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/home.png
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/index.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix03.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix04.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix05.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix06.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix07.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix08.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix09.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix10.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix11.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix12.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix13.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix14.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/ix15.html
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/left-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/left.png
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/right-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/right.png
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/style.css
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/up-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/up.png
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/ch01.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/ch02.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-1.0.devhelp2
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-adder.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-alsamidisrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-alsasink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-alsasrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-appsink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-appsrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-audioconvert.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-audiointerleave.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-audiomixer.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-audiorate.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-audioresample.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-audiotestsrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-cdparanoiasrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-clockoverlay.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-compositor.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-decodebin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-decodebin3.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-encodebin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-giosink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-giosrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-giostreamsink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-giostreamsrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glcolorbalance.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glcolorconvert.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glcolorscale.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gldeinterlace.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gldifferencematte.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gldownload.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-blur.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-bulge.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-fisheye.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-glow.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-heat.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-identity.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-laplacian.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-lumaxpro.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-mirror.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-sepia.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-sin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-sobel.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-square.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-squeeze.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-stretch.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-tunnel.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-twirl.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-xpro.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects-xray.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gleffects.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glfilterapp.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glfilterbin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glfiltercube.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glfilterglass.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glimagesink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glimagesinkelement.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glmixerbin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glmosaic.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gloverlay.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glshader.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glsinkbin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glsrcbin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glstereomix.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glstereosplit.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gltestsrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-gltransformation.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glupload.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glvideomixer.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glvideomixerelement.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-glviewconvert.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-multifdsink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-multisocketsink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-oggaviparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-oggdemux.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-oggmux.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-oggparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-ogmaudioparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-ogmtextparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-ogmvideoparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-opusdec.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-opusenc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-overlaycomposition.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-parsebin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-playbin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-playbin3.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-playsink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-adder.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-alsa.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-app.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-audioconvert.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-audiomixer.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-audiorate.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-audioresample.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-audiotestsrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-cdparanoia.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-compositor.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-encoding.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-gio.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-ivorbisdec.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-libvisual.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-ogg.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-opengl.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-opus.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-overlaycomposition.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-pango.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-playback.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-rawparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-subparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-tcp.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-theora.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-typefindfunctions.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-videoconvert.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-videorate.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-videoscale.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-videotestsrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-volume.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-vorbis.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-ximagesink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-plugin-xvimagesink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-rawaudioparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-rawvideoparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-socketsrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-ssaparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-streamsynchronizer.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-subparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-subtitleoverlay.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-tcpclientsink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-tcpclientsrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-tcpserversink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-tcpserversrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-textoverlay.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-textrender.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-theoradec.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-theoraenc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-theoraparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-timeoverlay.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-unalignedaudioparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-unalignedvideoparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-uridecodebin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-urisourcebin.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-videoconvert.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-videorate.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-videoscale.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-videotestsrc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-volume.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-vorbisdec.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-vorbisenc.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-vorbisparse.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-vorbistag.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-ximagesink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/gst-plugins-base-plugins-xvimagesink.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/home.png
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/index.html
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/left-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/left.png
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/right-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/right.png
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/style.css
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/up-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-base-plugins-1.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/gstreamer-1.0/libgstadder.so
/usr/lib64/gstreamer-1.0/libgstalsa.so
/usr/lib64/gstreamer-1.0/libgstapp.so
/usr/lib64/gstreamer-1.0/libgstaudioconvert.so
/usr/lib64/gstreamer-1.0/libgstaudiomixer.so
/usr/lib64/gstreamer-1.0/libgstaudiorate.so
/usr/lib64/gstreamer-1.0/libgstaudioresample.so
/usr/lib64/gstreamer-1.0/libgstaudiotestsrc.so
/usr/lib64/gstreamer-1.0/libgstcompositor.so
/usr/lib64/gstreamer-1.0/libgstencoding.so
/usr/lib64/gstreamer-1.0/libgstgio.so
/usr/lib64/gstreamer-1.0/libgstogg.so
/usr/lib64/gstreamer-1.0/libgstopengl.so
/usr/lib64/gstreamer-1.0/libgstopus.so
/usr/lib64/gstreamer-1.0/libgstoverlaycomposition.so
/usr/lib64/gstreamer-1.0/libgstpango.so
/usr/lib64/gstreamer-1.0/libgstpbtypes.so
/usr/lib64/gstreamer-1.0/libgstplayback.so
/usr/lib64/gstreamer-1.0/libgstrawparse.so
/usr/lib64/gstreamer-1.0/libgstsubparse.so
/usr/lib64/gstreamer-1.0/libgsttcp.so
/usr/lib64/gstreamer-1.0/libgsttheora.so
/usr/lib64/gstreamer-1.0/libgsttypefindfunctions.so
/usr/lib64/gstreamer-1.0/libgstvideoconvert.so
/usr/lib64/gstreamer-1.0/libgstvideorate.so
/usr/lib64/gstreamer-1.0/libgstvideoscale.so
/usr/lib64/gstreamer-1.0/libgstvideotestsrc.so
/usr/lib64/gstreamer-1.0/libgstvolume.so
/usr/lib64/gstreamer-1.0/libgstvorbis.so
/usr/lib64/gstreamer-1.0/libgstximagesink.so
/usr/lib64/gstreamer-1.0/libgstxvimagesink.so
/usr/lib64/libgstallocators-1.0.so.0
/usr/lib64/libgstallocators-1.0.so.0.1600.0
/usr/lib64/libgstapp-1.0.so.0
/usr/lib64/libgstapp-1.0.so.0.1600.0
/usr/lib64/libgstaudio-1.0.so.0
/usr/lib64/libgstaudio-1.0.so.0.1600.0
/usr/lib64/libgstfft-1.0.so.0
/usr/lib64/libgstfft-1.0.so.0.1600.0
/usr/lib64/libgstgl-1.0.so.0
/usr/lib64/libgstgl-1.0.so.0.1600.0
/usr/lib64/libgstpbutils-1.0.so.0
/usr/lib64/libgstpbutils-1.0.so.0.1600.0
/usr/lib64/libgstriff-1.0.so.0
/usr/lib64/libgstriff-1.0.so.0.1600.0
/usr/lib64/libgstrtp-1.0.so.0
/usr/lib64/libgstrtp-1.0.so.0.1600.0
/usr/lib64/libgstrtsp-1.0.so.0
/usr/lib64/libgstrtsp-1.0.so.0.1600.0
/usr/lib64/libgstsdp-1.0.so.0
/usr/lib64/libgstsdp-1.0.so.0.1600.0
/usr/lib64/libgsttag-1.0.so.0
/usr/lib64/libgsttag-1.0.so.0.1600.0
/usr/lib64/libgstvideo-1.0.so.0
/usr/lib64/libgstvideo-1.0.so.0.1600.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gst-plugins-base/COPYING
/usr/share/package-licenses/gst-plugins-base/gst-libs_gst_tag_licenses.c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gst-device-monitor-1.0.1
/usr/share/man/man1/gst-discoverer-1.0.1
/usr/share/man/man1/gst-play-1.0.1

%files locales -f gst-plugins-base-1.0.lang
%defattr(-,root,root,-)

